spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/chat/
    suffix: .html
    cache: false
  jwt:
    secret-key: 123498765L
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/chat_service
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8099
